-- ============================================================================
--  cian — 設定ファイル（日本語版）
-- ============================================================================
--
--  以下はすべてコメントアウトされています。行頭の "-- " を消せば、その設定が
--  有効になります。何も外さなければ、cian は既定値で動きます。
--
--  このファイルの置き場所:
--    Linux / macOS : ~/.config/cian/init.lua
--    Windows       : %USERPROFILE%\.config\cian\init.lua
--                    （例: C:\Users\you\.config\cian\init.lua）
--    もしくは $CIAN_CONFIG_DIR を設定すれば、cian は
--    $CIAN_CONFIG_DIR/init.lua を読みます。
--
--  ※ このファイル自体は英語版 examples/init.lua の日本語訳です。中身のコードは
--     同じなので、好きな方をコピーして使ってください。
--
--  init.lua をすっきり保つ：SSH ホストとキーバインドは、それぞれ隣の別ファイル
--  （ssh.lua / keymap.lua、examples/ を参照）に分けられます。cian は init.lua の
--  直後に同じ設定として読み込むので、`cian.ssh{…}` / `cian.set_keymap(…)` は
--  そこでもここと同じように効きます。これで init.lua を「画面表示・Git/SVN・AI」
--  に集中させられます。読み込まれているファイルは `:where` で確認できます。
--
--  中身は素の Lua 5.4 です。変数・関数・`if` を自由に使えます（例: マシンごとに
--  別のシェルを指定するなど）。書き間違えても致命的にはならず、cian は起動時に
--  まとめて通知するだけで、そのまま動きます。
--
--  キー一覧はいつでも、アプリ内で `?`、`:man`、または `cian -man` で見られます。
-- ============================================================================


-- ----------------------------------------------------------------------------
--  テーマ
-- ----------------------------------------------------------------------------
-- 名前付きプリセットから始められます。内蔵プリセット:
--   "default" / "dark"        （内蔵のダークテーマ。既定値）
--   "solarized-light"         （別名 "solarized"）、"solarized-dark"
--   "dracula", "nord", "monokai", "one-dark", "tokyo-night"
--   "gruvbox-dark", "gruvbox-light"
--   "catppuccin-mocha"（別名 "catppuccin"）、"catppuccin-latte"
--   "github-light", "bluloco-light"
--   "monokai-pro", "ayu-dark", "ayu-light", "bearded"
-- cian.set_theme "dracula"
--
-- 実行中にも切り替えられます（再起動不要）。`:theme` でギャラリーが開き、各
-- プリセットをライブでプレビューできます（Enter で決定、Esc で取消）。
-- `:theme <名前>` で直接指定も可。右クリックメニューからも開けます。
-- この方法で選んだテーマは記憶され（設定の隣の state.toml に保存。場所は
-- `:where` で確認）、次回起動時に再適用されます。上の cian.set_theme より優先
-- されるので、この行は実質「既定値」の指定になります。

-- …または個別の色を調整することもできます。値は "#rrggbb" か色名
-- （"yellow", "cyan" など）。指定しなかったキーは現在値を保ちます。プリセット
-- と上書きの併用も可能です:
-- cian.set_theme {
--   preset      = "solarized-light",  -- 起点にするプリセット（任意）
--   accent      = "#268bd2",  -- フォーカス枠・ハイライト・バーの色
--   status_bg   = "#eee8d5",  -- 下部ステータス行の背景
--   selected_bg = "#dcd5be",  -- 選択行のハイライト背景
--   visual_bg   = "#f7e4b0",  -- ビジュアル選択中のハイライト
--   mark_fg     = "#cb4b16",  -- マーク済みファイルの ● の色
-- }


-- ----------------------------------------------------------------------------
--  オプション  —  cian.set_option(name, value)
-- ----------------------------------------------------------------------------

-- パス引数なしで cian を起動したとき、両ペインが開くディレクトリ。既定では
-- デスクトップ、次にホームフォルダ。ショートカットから起動する場合など、作業
-- ディレクトリが exe の場所になってしまうときに便利です。
-- cian.set_option("home", "C:\\Users\\you\\Desktop")   -- Windows
-- cian.set_option("home", "~/Desktop")                 -- Linux / macOS（~ と $VAR は展開されます）

-- 埋め込みシェルパネルで動かすシェル。既定は $SHELL / %COMSPEC%。
-- cian.set_option("shell", "powershell.exe")
-- cian.set_option("shell", "pwsh.exe")     -- PowerShell 7
-- cian.set_option("shell", "/bin/zsh")

-- `y` でコピーしたとき、システムのクリップボードにもファイルを載せる（エクス
-- プローラー / Finder にも貼り付けられる）。既定: true。

-- SFTP のアップロード/ダウンロード後、リモートのファイルを読み直してローカルと
-- チェックサムを比較し、不一致なら警告する。既定: false（データをもう一度読む
-- ため、帯域より整合性が大事なときだけ有効に）。SFTP が必要（SCP フォールバック
-- は読み直せない）。
-- cian.set_option("verify_transfers", true)

-- 長い処理（コピー／移動／削除・圧縮・転送）が終わったら、端末のベルを鳴らし
-- デスクトップ通知（OSC 9）を出す。大きなコピーを走らせて席を外したときのため。
-- 既定: true。対応端末は Windows Terminal と iTerm2（非対応端末は無視します）。
-- cian.set_option("notify", false)

-- サーバとの転送速度の上限（未設定なら無制限）。"2M" "500k" "1.5MB/s" のように書きます。
-- セッション中は `:limit 2M` / `:limit off` でも変えられます。
-- cian.set_option("transfer_limit", "2M")
-- 通知が出るまでに処理が最低何秒かかっている必要があるか。既定: 5（短い処理は
-- 鳴りません）。
-- cian.set_option("notify_min_secs", 10)

-- 起動時にドットファイル（"." で始まる名前）を表示する。右クリックメニューで
-- ライブに切り替え可能。既定: true。
-- cian.set_option("show_hidden", true)

-- Nerd Font グリフ — ファイル種別アイコンや、ステータス行のブランチ／ディスク
-- 記号。既定 true。Nerd Font の入っていない端末では false にすると、それらの
-- グリフを出さなくなります（文字化け防止）。フォルダは色で識別できます。
-- cian.set_option("nerd_fonts", false)

-- 書体 — **窓版だけの設定です。** 端末版の書体はエミュレータのものなので、
-- サイズと同じ理由で cian からは触れません。窓版は Chromium で描いているので
-- 教えられます。同梱の HackGen Console NF は後ろに残るため、選んだ書体に字形の
-- 無い文字（欧文専用の Nerd Font に日本語を描かせたとき等）でも列は崩れません。
-- 入っていない書体は一度そう言い、`:version` が実際に使われた書体を出します。
-- cian.font{ face = "JetBrainsMono Nerd Font" }

-- 枠線の角: "rounded"（╭╮╯╰）か "plain"（直角）。未設定なら自動判定 —
-- 描画できる端末／フォントでは丸角、レガシー Windows コンソールでは直角。
-- 角がずれて見えるときは "plain" を強制してください。
-- cian.set_option("borders", "rounded")

-- ステータス行の上に出る、状況に応じたキーヒントバー。既定: true。キー操作が
-- 手に馴染んだら false にして画面をすっきりさせられます。
-- cian.set_option("key_hints", true)

-- インターフェースの言語（キー一覧、ステータス行、メニュー、ダイアログ）。
-- 既定: "ja"（日本語）。コメントを外すと英語になります。
-- （右クリックメニューからライブに切り替えることもできます。）
-- cian.set_option("lang", "en")

-- カーソル追従プレビューの対象外にする拡張子（ドットは有無どちらでも、
-- 大文字小文字は問いません）。ここに書いたものは**既定の一覧に追加**されます。
-- 既定で対象外：vsix jar war whl apk ipa nupkg crx xpi msix などの
-- 「中を見るためのものではない zip」、iso dmg vmdk vhd wim などのイメージ、
-- msi deb rpm cab などのインストーラ、pdf、mdf ldf sqlite pst などの DB。
-- zip / tar / 7z は**対象外にしていません** — こちらは中を見るために開くので。
-- F3 ではどれも開けます — これは「頼んでいないのに開く」のを止める設定です。
-- cian.set_option("preview_skip", { "bak", "dmp" })

-- キー一覧（`?`）と右クリックメニューだけの言語。この 2 か所だけ `lang` を
-- 上書きします。インターフェースは英語のままメニュー／マニュアルだけ日本語で
-- 読む（またはその逆）のに便利。未設定なら `lang` に従います。
-- cian.set_option("menu_lang", "ja")

-- 分割 / ズーム / クローズのアニメーション時間（ミリ秒）。0 で全アニメーション
-- を無効化。既定は短くきびきびした遷移です。
-- cian.set_option("animation_ms", 120)
-- cian.set_option("animation_ms", 0)      -- 無効

-- F3 ビューアの `E` と `:edit` で使う外部エディタ。コマンドラインを指定し、末尾
-- にファイルパスが付きます。未設定なら $VISUAL / $EDITOR、次に PATH 上の
-- nvim → vim → vi の順で最初に見つかったものを使います（どれも無ければその旨
-- を表示）。
-- cian.set_option("editor", "nvim")
-- cian.set_option("editor", "code -w")   -- VS Code（タブを閉じるまで待機）


-- ----------------------------------------------------------------------------
--  キーバインド  —  cian.set_keymap("key", "action")
-- ----------------------------------------------------------------------------
-- `key` は 1 文字です。キーにアクションを割り当てると、ファイルペインでその
-- キーがアクションを起動します。使い方は 3 通り:
--
--   * キーを追加:  cian.set_keymap("x", "delete")   -- x でも削除できるように
--   * キーを変更:  既定のあるキーに割り当てると既定を置き換えます。
--                  `cian.set_keymap("d", "rename")` で `d` は削除ではなく
--                  リネームになります。
--   * キーを無効化: "none" に割り当てます。 cian.set_keymap("d", "none")
--
-- 以下は既定のバインドを、それを再現する行として並べたものです。既に有効なので
-- コメントアウトしてあります — 移動したい（"key" を変える）か、無効化したい
-- （"none"）ときだけコメントを外してください。構造キー（矢印、Enter、
-- Backspace、Tab、F キー、Ctrl-／Shift- の組み合わせ）は組み込みで、ここでは
-- 再割り当てできません。以下はすべて変更可能です。
--
--   -- 移動
--   cian.set_keymap("j", "cursor_down")
--   cian.set_keymap("k", "cursor_up")
--   cian.set_keymap("g", "cursor_top")      -- （`gg` コード。下の注記を参照）
--   cian.set_keymap("G", "cursor_bottom")
--   cian.set_keymap("D", "page_down")
--   cian.set_keymap("U", "page_up")
--   cian.set_keymap("l", "enter")           -- 選択中のディレクトリに入る
--   cian.set_keymap("-", "parent")          -- 親ディレクトリへ上がる
--
--   -- マーク / 選択
--   cian.set_keymap(" ", "mark_down")       -- スペース: マーク切替＋下へ
--   cian.set_keymap("v", "visual")          -- ビジュアル（範囲）選択モード
--   cian.set_keymap("V", "invert_marks")
--
--   -- ファイル操作
--   cian.set_keymap("c", "copy")            -- 反対ペインへコピー
--   cian.set_keymap("m", "move")            -- 反対ペインへ移動
--   cian.set_keymap("y", "paste")           -- ファイルクリップボードを貼り付け（= Ctrl+V）
--   -- Windows流のファイルクリップボードは Ctrl+C / Ctrl+X / Ctrl+V にも割当済み。
--   -- （再割当できるアクション名: copy, move, paste, cut, delete, …）
--   cian.set_keymap("d", "delete")          -- ゴミ箱へ
--   cian.set_keymap("r", "rename")
--   cian.set_keymap("a", "new_file")
--   cian.set_keymap("A", "new_dir")
--   cian.set_keymap("o", "sync_from_other") -- このペイン → 反対ペインのディレクトリ
--   cian.set_keymap("O", "sync_to_other")   -- 反対ペイン → このペインのディレクトリ
--   -- （反対ペインで開く操作は Ctrl+Enter にあります。文字キーが好みなら
--   --  ここで割り当ててください: cian.set_keymap("o", "open_other"))
--   cian.set_keymap("e", "open_external")   -- ファイルを OS の関連付けで開く
--
--   -- クリップボード
--   cian.set_keymap("p", "copy_path")       -- パス文字列をコピー
--   cian.set_keymap("P", "copy_file_ref")   -- ファイル参照をコピー（Finder/エクスプローラー）
--
--   -- 検索 / 絞り込み / 並べ替え
--   cian.set_keymap("f", "search")          -- この一覧内を検索
--   cian.set_keymap("n", "search_next")
--   cian.set_keymap("N", "search_prev")
--   cian.set_keymap("/", "filter")          -- インクリメンタル絞り込み
--   cian.set_keymap("F", "find_recursive")  -- 名前でファイルを再帰検索
--   cian.set_keymap(",", "sort")            -- 並べ替え順のピッカーを開く
--   cian.set_keymap("z", "jump_path")       -- 入力したパスへジャンプ
--   cian.set_keymap("=", "diff")            -- 両ペインのファイルを比較
--
--   -- タブ、パネル、ツール
--   cian.set_keymap("t", "new_tab")
--   cian.set_keymap("w", "close_tab")
--   cian.set_keymap("h", "history")
--   cian.set_keymap("s", "shortcuts")       -- ブックマークメニュー
--   cian.set_keymap("M", "menu")            -- 右クリックのコンテキストメニュー
--                                           -- （端末が報告できる環境では
--                                           --  Shift+Enter でも開けます）
--   cian.set_keymap(":", "command")         -- : コマンドライン
--   cian.set_keymap("q", "quit")
--
-- アクション名の一覧（第 2 引数に使えるもの）:
--   移動     : cursor_down  cursor_up  cursor_top  cursor_bottom
--              page_down  page_up  parent  enter
--   マーク   : mark_down  mark_up  invert_marks  visual
--   ファイル : copy  move  paste  cut  delete  rename  new_file  new_dir
--              open_other  open_other_tab  open_external
--              sync_from_other  sync_to_other
--   クリップ : copy_path  copy_file_ref
--   検索     : search  search_next  search_prev  filter
--              find_recursive  grep_recursive  sort  jump_path  diff
--   パネル   : new_tab  close_tab  history  shortcuts  ssh  view  menu
--   その他   : refresh  manual  command  quit  none  （none はキーを無効化）
--
-- 注記: `cursor_top` は `gg` コード（g を 2 回）に割り当てられています。1 キー
-- では再現できない vim 由来の操作なので、ここに名前を挙げているのはマニュアルに
-- 載せるためだけです。`grep_recursive`（ファイル内容の検索）には既定の文字が
-- ありません。使いたいなら割り当ててください。例:
-- cian.set_keymap("G", "grep_recursive")。


-- ----------------------------------------------------------------------------
-- ----------------------------------------------------------------------------
--  SharePoint の場所を、パスとして書く
-- ----------------------------------------------------------------------------
--  cian は SharePoint に**接続しません**。Windows が WebDAV として開けるように
--  URL を UNC パスへ直すだけです。だから `z` にも、設定のどこにでも、
--  SharePoint の URL をそのまま書けます:
--
--    https://jri.sharepoint.com/sites/Team/Shared Documents/notes
--        ↓ cian が直します
--    \\jri.sharepoint.com@SSL\DavWWWRoot\sites\Team\Shared Documents\notes
--
--  **アドレス欄の URL をコピーしてください。**「リンクをコピー」で作る共有リンク
--  （`/:x:/s/…`）には場所が入っていないので使えません ── そのときは cian が
--  そう言います。
--
--  開けないときは、Windows がまだ「つないでよい」と覚えていません。
--  ① Edge でその *フォルダ* を開く
--  ② そのタブを Internet Explorer モードで読み直す
--     （「Edge で表示してください」と出ますが、それで正しいです）
--  ③ エクスプローラーのアドレス欄に同じパスを入れて開く
--  **この接続はサインアウトや再起動で切れます。**
--
--  SSH ホスト  —  cian.ssh { ... }
-- ----------------------------------------------------------------------------
-- SSH ピッカー（右クリック → SSH 接続、またはシェル内から）と、ファイルの
-- アップロード／ダウンロードで使うホストを登録します。転送は SFTP を使い、
-- サーバに SFTP サブシステムが無ければ自動で古典的な SCP プロトコルに
-- フォールバックします。どちらで転送したかはステータス行に表示されます。
-- トップレベルの `users` は全ホスト共通の既定で、ホストごとに上書きできます。
-- user は名前だけの文字列か、パスワードを持たせたテーブル（cian が自動ログイン
-- するため）のどちらかです。
--
-- セキュリティ注意: ここに平文 `password` を書くと、このファイルに平文で保存
-- されます。可能なら `password_cmd` を使ってください。コマンドを実行してその
-- 標準出力を使うので、秘密情報は OS の資格情報ストアに置け、ディスクに
-- 残りません。
--
-- cian.ssh {
--   -- 自前の users を持たない全ホストに適用される既定:
--   users = { "root", "deploy" },
--
--   hosts = {
--     -- 最小形: ピッカー用の名前とアドレス。既定の users を使う。
--     { name = "web1", host = "10.0.1.11" },
--
--     -- 非標準ポート:
--     { name = "db1",  host = "10.0.2.31", port = 2222 },
--
--     -- ホストごとの users。1 つは自動ログイン用にパスワードを記載:
--     { name = "stage", host = "stage.example.com",
--       users = {
--         "readonly",                                    -- 都度入力、自動ログインなし
--         { name = "admin", password = "hunter2" },      -- 平文（非推奨）
--         { name = "ci",    password_cmd = "pass show ci/stage" },  -- ストアから取得
--
--         -- 鍵で入る（推奨）。パスワードをどこにも置かずに済みます。`~` は
--         -- 展開されます。**パスワードより先に鍵を試し**、断られたら
--         -- パスワードに落ちるので、両方書いておけます。
--         { name = "deploy", key = "~/.ssh/id_ed25519" },
--         { name = "old",    key = "~/.ssh/id_rsa", key_pass = "…" },
--       },
--     },
--
--     -- `notes` はサーバに関する事実（OS、ミドル、バージョン）を記録します。
--     -- ここにシェル接続すると、その内容が AI に伝わります（ai_context 参照）。
--     { name = "db1", host = "10.0.2.31",
--       notes = "RHEL 8.9; Oracle 19c; /u01 の空きが少ない" },
--   },
-- }


-- ----------------------------------------------------------------------------
--  AI  —  cian.ai { ... }   （任意。Python + Azure OpenAI アクセスが必要）
-- ----------------------------------------------------------------------------
-- cian の AI 機能（`:ai` チャット、後々のジャンク検出／構成提案など）を有効に
-- します。cian は同梱の小さな Python ヘルパー経由で Azure OpenAI と通信し、
-- Windows ブローカー（WAM）認証を使います。Python・パッケージ・
-- サインインのいずれかが使えなければ AI 機能は静かに無効化され、cian はこれまで
-- どおり動作します。このブロックが無ければ AI は完全にオフです。
--
-- ヘルパーには次の Python パッケージが必要です: `openai`、ブローカー認証用に
-- `azure-identity-broker`（サインインダイアログの親ウィンドウ用に `pywin32`）。
-- モデルに送るのは各機能が必要とする分だけ（ファイル名とサイズ。ファイル内容は
-- 機能が明示的に要求する場合のみ）です。
--
-- エンドポイントは既定では空です。組織の API ゲートウェイのアドレスは、
-- 公開リポジトリのソースではなく、その組織の init.lua に書くべきものなので。
-- 未設定のまま AI 機能を使うと、何を設定すればよいかを表示して止まります。
--
-- 設定例:
-- cian.ai {
--   endpoint    = "https://your-apim.azure-api.net/llmaoai",  -- Azure OpenAI / APIM
--   model       = "gpt-5-mini",
--   auth_mode   = "broker",    -- "broker"（Windows AAD）、"apikey"、"mock"（オフラインのエコー）
--   -- python   = "python",    -- 使うインタプリタ（既定: "python"）
--   -- api_version  = "2025-04-01-preview",
--   -- api_key      = "...",   -- auth_mode = "apikey" のときだけ
--   -- api_base_url = "http://localhost:11434/v1",  -- Ollama / LM Studio（OpenAI 互換）
-- }
--
-- 404「Resource not found」が出る? ブローカー／Azure 認証では `model` は
-- デプロイ名であり、リクエスト URL に入ります
-- （…/openai/deployments/<model>/chat/…）。ここが違うと 404 になります —
-- 動作しているクライアントに合わせて `model`（と `api_version`）を設定して
-- ください。もしゲートウェイが OpenAI 互換（model をボディに入れて
-- /chat/completions を叩く形式で、/openai/deployments/ パスではない）なら、
-- `api_base_url` にゲートウェイのベースを設定すれば、cian はブローカートークンで
-- そのルートを使います:
-- cian.ai {
--   auth_mode    = "broker",
--   api_base_url = "https://your-apim.azure-api.net/llmaoai",  -- OpenAI 互換ルート
--   model        = "<あなたのモデル>",
-- }
--

-- ----------------------------------------------------------------------------
--  日本語入力（IME）── vim のキー操作を使うなら、ほぼ必須です
-- ----------------------------------------------------------------------------
--  **IME がオンのままだと、ノーマルモードのキーは cian に届きません。**
--  変換中の文字は入力方式が握っていて、`j` も `i` も `?` も、確定するまで
--  こちらには来ません。端末版でも窓版でも同じで、vim が `im-select` の類を
--  必要とするのと同じ理由です。
--
--  設定すると、cian が**モードに合わせて自分で切り替えます** ── キーが
--  コマンドのときは常にオフ、文字を打つ場面（挿入モード・リネーム・
--  コマンド行）では**直前にあなたが使っていた入力ソース**に戻します。
--
--  ヘルパーは cian に同梱しています。外部から入れるものはありません。
--
--  macOS ── 一度コンパイルするだけ（OS の API を叩く30行）:
--    swiftc -O -o ~/.local/bin/cian-ime examples/cian-ime.swift
--
-- cian.ime{
--   helper = "$HOME/.local/bin/cian-ime",
--   off    = "com.apple.keylayout.ABC",   -- `cian-ime` を引数なしで実行すると
-- }                                       -- いまの入力ソース ID が出ます
--
--  Windows ── コンパイル不要。PowerShell がそのまま実行します:
--
-- cian.ime{
--   helper = [[powershell -NoProfile -File C:\Users\you\cian-ime.ps1]],
--   off    = "off",
-- }
--
--  ※ Windows の IME は **窓ごとにオン／オフ**で、macOS の「入力ソースを
--    切り替える」とは別のものです。だから id は "on" / "off" の2語だけ。
--    cian は中身を見ないので、これで同じ仕組みが成立します。
--
--  `macism` や `im-select` を既に入れているならそれでも構いません
--  （`helper = "macism"`）。変わったヘルパーなら `query` と `set` を個別に
--  指定できます（`set = "switch --to {}"`）。
--
--  **`:ime` が診断です。** 設定・記憶している入力ソース・直前の切替結果を
--  表示します。`:ime on` / `:ime off` でその場で試せます。
