-- ============================================================================
--  cian — configuration
-- ============================================================================
--
--  Everything below is COMMENTED OUT. Delete the leading "-- " on any line to
--  turn that setting on. With nothing uncommented, cian runs on its defaults.
--
--  Where this file goes:
--    Linux / macOS : ~/.config/cian/init.lua
--    Windows       : %USERPROFILE%\.config\cian\init.lua
--                    (e.g. C:\Users\you\.config\cian\init.lua)
--    Or set $CIAN_CONFIG_DIR to point somewhere else; cian reads
--    $CIAN_CONFIG_DIR/init.lua then.
--
--  It is plain Lua 5.4, so you can use variables, functions and `if` around
--  any of this (e.g. a different shell per machine). Mistakes are never fatal:
--  cian collects them and shows a notice on startup instead of refusing to run.
--
--  See the full key list any time with `?` in the app, `:man`, or `cian -man`.
--
--  日本語版はこのファイルの日本語訳 examples/init.ja.lua にあります。
--
--  Keeping init.lua tidy: the SSH hosts and the key bindings can each move to
--  their own file next to this one — ssh.lua and keymap.lua (see examples/).
--  cian loads them right after init.lua into the same config, so `cian.ssh{…}`
--  and `cian.set_keymap(…)` work there exactly as they do here. That lets
--  init.lua stay focused on display, Git/SVN and AI. `:where` shows which files
--  are found.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  THEME
-- ----------------------------------------------------------------------------
-- Start from a named preset. Built in:
--   "default" / "dark"        (the built-in dark theme, the default)
--   "solarized-light"         (aka "solarized"),  "solarized-dark"
--   "dracula", "nord", "monokai", "one-dark", "tokyo-night"
--   "gruvbox-dark", "gruvbox-light"
--   "catppuccin-mocha" (aka "catppuccin"), "catppuccin-latte"
--   "github-light", "bluloco-light"
--   "monokai-pro", "ayu-dark", "ayu-light", "bearded"
-- cian.set_theme "dracula"
--
-- You can also switch at runtime — no restart needed: `:theme` opens a gallery
-- that previews each preset live (Enter keeps it, Esc cancels), or
-- `:theme <name>` sets one directly. It's also under the right-click menu.
-- A theme chosen this way is remembered (saved to state.toml next to your
-- config — see `:where`) and re-applied on the next launch, taking precedence
-- over the cian.set_theme above. So this line is really just the default.

-- …or tune individual colors. Values are "#rrggbb" or a color name
-- ("yellow", "cyan", …). Any key you leave out keeps its current value, and a
-- preset can be combined with overrides:
-- cian.set_theme {
--   preset      = "solarized-light",  -- optional base to start from
--   accent      = "#268bd2",  -- focused borders, highlights, the bar
--   status_bg   = "#eee8d5",  -- background of the bottom status line
--   selected_bg = "#dcd5be",  -- highlight behind the selected row
--   visual_bg   = "#f7e4b0",  -- highlight while marking in visual mode
--   mark_fg     = "#cb4b16",  -- color of the ● on marked files
-- }


-- ----------------------------------------------------------------------------
--  OPTIONS  —  cian.set_option(name, value)
-- ----------------------------------------------------------------------------

-- The directory both panes open in when cian is started with no path argument.
-- Defaults to the Desktop, then your home folder. Handy when launched from a
-- shortcut, where the working directory would otherwise be wherever the exe is.
-- cian.set_option("home", "C:\\Users\\you\\Desktop")   -- Windows
-- cian.set_option("home", "~/Desktop")                 -- Linux / macOS (~ and $VARS expand)

-- Which shell runs in the embedded shell panel. Defaults to $SHELL / %COMSPEC%.
-- cian.set_option("shell", "powershell.exe")
-- cian.set_option("shell", "pwsh.exe")     -- PowerShell 7
-- cian.set_option("shell", "/bin/zsh")

-- Also put files on the SYSTEM clipboard when you copy with `y` (so they paste
-- in Explorer / Finder too). Default: true.

-- After an SFTP upload/download, re-read the remote file and compare its
-- checksum with the local one, warning on a mismatch. Default: false (it reads
-- the data a second time, so turn it on when integrity matters more than
-- bandwidth). Needs SFTP — the SCP fallback cannot be re-read.
-- cian.set_option("verify_transfers", true)

-- When a long job (copy/move/delete, archive, transfer) finishes, ring the
-- terminal bell and post a desktop notification (OSC 9) — for when you start a
-- big copy and walk away. Default: true. Windows Terminal and iTerm2 support
-- it; other terminals ignore it.
-- cian.set_option("notify", false)

-- A ceiling on transfers to and from a server (unset = as fast as the link
-- allows). Written like a speed: "2M", "500k", "1.5MB/s". `:limit 2M` and
-- `:limit off` change it for the session.
-- cian.set_option("transfer_limit", "2M")
-- How many seconds a job must run before the finish notification fires.
-- Default: 5, so quick operations stay silent.
-- cian.set_option("notify_min_secs", 10)

-- Show dotfiles (names starting with ".") on startup. Toggle live with the
-- right-click menu. Default: true.
-- cian.set_option("show_hidden", true)

-- Nerd Font glyphs — the file-type icons and the branch / disk symbols in the
-- status line. Default true. Set false on a terminal WITHOUT a Nerd Font so
-- those glyphs are dropped (no mojibake); folders are still marked by colour.
-- cian.set_option("nerd_fonts", false)

-- The typeface — **the window build only.** A terminal's face is the
-- emulator's, for the same reason its size is; the window draws through
-- Chromium and can be told. The bundled HackGen Console NF stays behind this
-- one, so a character the chosen face has no glyph for (Japanese in a
-- Latin-only Nerd Font, say) does not break the columns. A face that is not
-- installed is said once, and `:version` reports the one actually used.
-- cian.font{ face = "JetBrainsMono Nerd Font" }

-- Border corners: "rounded" (╭╮╯╰) or "plain" (square). Unset auto-picks —
-- rounded where the terminal/font can render them, square in the legacy
-- Windows console. Force "plain" if the corners look misaligned.
-- cian.set_option("borders", "rounded")

-- The contextual key-hint bar above the status line. Default: true. Set false
-- for a cleaner screen once the keys are muscle memory.
-- cian.set_option("key_hints", true)

-- Interface language (the key manual, status line, menus, dialogs).
-- Default: "ja" (Japanese) — cian is written in Japanese first. Uncomment to
-- switch it to English.
-- (You can also toggle live from the right-click menu.)
-- cian.set_option("lang", "en")

-- Extensions the cursor-follow preview leaves alone (with or without the dot,
-- case-insensitive). What you put here is *added* to the built-in list.
-- Skipped by default: zip-based packages nobody browses as archives (vsix,
-- jar, war, whl, apk, ipa, nupkg, crx, xpi, msix…), disc and disk images
-- (iso, dmg, vmdk, vhd, wim…), installers (msi, deb, rpm, cab), PDFs and databases
-- (mdf, ldf, sqlite, pst). Plain archives — zip, tar, 7z — are *not* skipped:
-- listing one is the point of opening it. F3 opens any of them; this is about
-- what happens *without* being asked.
-- cian.set_option("preview_skip", { "bak", "dmp" })

-- Language for JUST the key manual (`?`) and the right-click context menu,
-- overriding `lang` for those two surfaces only. Handy to keep the interface in
-- English but read the menu / manual in Japanese (or vice versa). Unset =
-- follow `lang`.
-- cian.set_option("menu_lang", "ja")

-- Split / zoom / close animation length, in milliseconds. 0 disables all
-- animation. Default is a short, snappy transition.
-- cian.set_option("animation_ms", 120)
-- cian.set_option("animation_ms", 0)      -- off

-- External editor for `E` in the F3 viewer and `:edit`. A command line; the
-- file is appended. Unset falls back to $VISUAL / $EDITOR, then the first of
-- nvim -> vim -> vi found on PATH (and if none is found, cian says so).
-- cian.set_option("editor", "nvim")
-- cian.set_option("editor", "code -w")   -- VS Code, waiting for the tab to close


-- ----------------------------------------------------------------------------
--  KEY BINDINGS  —  cian.set_keymap("key", "action")
-- ----------------------------------------------------------------------------
-- `key` is one character. Binding a key to an action makes that key trigger it
-- in the file panes. This works two ways:
--
--   * ADD a key:      cian.set_keymap("x", "delete")   -- x now deletes too
--   * CHANGE a key:   binding a key that already has a default REPLACES the
--                     default. `cian.set_keymap("d", "rename")` makes `d`
--                     rename instead of delete.
--   * DISABLE a key:  bind it to "none".  cian.set_keymap("d", "none")
--
-- The DEFAULT bindings are listed below, each as the line that would recreate
-- it. They are commented out because they are already active — uncomment one
-- only to move it (change the "key") or turn it off ("none"). Structural keys
-- (arrows, Enter, Backspace, Tab, the F-keys, and Ctrl-/Shift- combos) are
-- built in and not remappable here; everything below is.
--
--   -- Movement
--   cian.set_keymap("j", "cursor_down")
--   cian.set_keymap("k", "cursor_up")
--   cian.set_keymap("g", "cursor_top")      -- (the `gg` chord; see note)
--   cian.set_keymap("G", "cursor_bottom")
--   cian.set_keymap("D", "page_down")
--   cian.set_keymap("U", "page_up")
--   cian.set_keymap("l", "enter")           -- enter the highlighted directory
--   cian.set_keymap("-", "parent")          -- go up to the parent directory
--
--   -- Marking / selection
--   cian.set_keymap(" ", "mark_down")       -- space: toggle mark, move down
--   cian.set_keymap("v", "visual")          -- visual (range) select mode
--   cian.set_keymap("V", "invert_marks")
--
--   -- File operations
--   cian.set_keymap("c", "copy")            -- copy to the OTHER pane
--   cian.set_keymap("m", "move")            -- move to the OTHER pane
--   cian.set_keymap("y", "paste")           -- paste the file clipboard (= Ctrl+V)
--   -- Windows-style file clipboard is also on Ctrl+C / Ctrl+X / Ctrl+V.
--   -- (rebindable action names: copy, move, paste, cut, delete, …)
--   cian.set_keymap("d", "delete")          -- to the trash
--   cian.set_keymap("r", "rename")
--   cian.set_keymap("a", "new_file")
--   cian.set_keymap("A", "new_dir")
--   cian.set_keymap("o", "sync_from_other") -- this pane → other pane's dir
--   cian.set_keymap("O", "sync_to_other")   -- other pane → this pane's dir
--   -- (open-into-the-opposite-pane lives on Ctrl+Enter; bind it here if you
--   --  prefer a letter: cian.set_keymap("o", "open_other"))
--   cian.set_keymap("e", "open_external")   -- hand the file to the OS opener
--
--   -- Clipboard
--   cian.set_keymap("p", "copy_path")       -- copy path text
--   cian.set_keymap("P", "copy_file_ref")   -- copy a file reference (Finder/Explorer)
--
--   -- Find / filter / sort
--   cian.set_keymap("f", "search")          -- search within this listing
--   cian.set_keymap("n", "search_next")
--   cian.set_keymap("N", "search_prev")
--   cian.set_keymap("/", "filter")          -- incremental filter
--   cian.set_keymap("F", "find_recursive")  -- find files by name, recursively
--   cian.set_keymap(",", "sort")            -- open the sort-order picker
--   cian.set_keymap("z", "jump_path")       -- jump to a typed path
--   cian.set_keymap("=", "diff")            -- diff the two panes' files
--
--   -- Tabs, panels, tools
--   cian.set_keymap("t", "new_tab")
--   cian.set_keymap("w", "close_tab")
--   cian.set_keymap("h", "history")
--   cian.set_keymap("s", "shortcuts")       -- the bookmarks menu
--   cian.set_keymap("M", "menu")            -- the right-click context menu
--                                           -- (Shift+Enter also, where the
--                                           --  terminal can report it)
--   cian.set_keymap(":", "command")         -- the : command line
--   cian.set_keymap("q", "quit")
--
-- The full list of action names (for the second argument):
--   Movement : cursor_down  cursor_up  cursor_top  cursor_bottom
--              page_down  page_up  parent  enter
--   Marking  : mark_down  mark_up  invert_marks  visual
--   Files    : copy  move  paste  cut  delete  rename  new_file  new_dir
--              open_other  open_other_tab  open_external
--              sync_from_other  sync_to_other
--   Clipboard: copy_path  copy_file_ref
--   Find     : search  search_next  search_prev  filter
--              find_recursive  grep_recursive  sort  jump_path  diff
--   Panels   : new_tab  close_tab  history  shortcuts  ssh  view  menu
--   Misc     : refresh  manual  command  quit  none  (none disables the key)
--
-- Note: `cursor_top` is bound to the `gg` chord (press g twice), a vim-ism
-- that a single key cannot reproduce; naming it here is only so it appears in
-- the manual. `grep_recursive` (search file contents) has no default letter —
-- bind one if you want it, e.g. cian.set_keymap("G", "grep_recursive").


-- ----------------------------------------------------------------------------
--  SSH HOSTS  —  cian.ssh { ... }
-- ----------------------------------------------------------------------------
-- Populates the SSH picker (right-click → SSH connect, or in the shell) and the
-- file upload/download flow. Transfers use SFTP, falling back to the classic
-- SCP protocol automatically when the server has no SFTP subsystem; the status
-- line shows which one carried it. `users` at the top level is the fleet-wide default;
-- a host can override it. A user is either a bare name, or a table carrying its
-- password so cian can log in for you.
--
-- SECURITY NOTE: a plain `password` here is stored in clear text in this file.
-- Prefer `password_cmd`, which runs a command and uses its stdout — so the
-- secret lives in your OS credential store, not on disk.
--
-- cian.ssh {
--   -- Applied to every host that doesn't list its own users:
--   users = { "root", "deploy" },
--
--   hosts = {
--     -- Simplest: a name for the picker and an address. Uses the default users.
--     { name = "web1", host = "10.0.1.11" },
--
--     -- A non-standard port:
--     { name = "db1",  host = "10.0.2.31", port = 2222 },
--
--     -- Per-host users, one with a password typed in for auto-login:
--     { name = "stage", host = "stage.example.com",
--       users = {
--         "readonly",                                    -- prompts, no auto-login
--         { name = "admin", password = "hunter2" },      -- clear text (avoid)
--         { name = "ci",    password_cmd = "pass show ci/stage" },  -- from a store
--
--         -- A key (preferred): nothing secret need live on disk. `~` is
--         -- expanded. **The key is tried before the password** and a refused
--         -- key falls through to one, so both can be given.
--         { name = "deploy", key = "~/.ssh/id_ed25519" },
--         { name = "old",    key = "~/.ssh/id_rsa", key_pass = "…" },
--       },
--     },
--
--     -- `notes` records facts about the server (OS, middleware, versions).
--     -- When a shell is connected here, the AI is told them (see ai_context).
--     { name = "db1", host = "10.0.2.31",
--       notes = "RHEL 8.9; Oracle 19c; disk is tight on /u01" },
--   },
-- }


-- ----------------------------------------------------------------------------
--  AI  —  cian.ai { ... }   (optional; needs Python + Azure OpenAI access)
-- ----------------------------------------------------------------------------
-- Enables cian's AI features (`:ai` chat, and later junk detection / structure
-- suggestions). cian talks to Azure OpenAI through a small bundled Python
-- helper using Windows broker (WAM) auth. If Python, the
-- packages, or sign-in are unavailable, the AI features stay silent — cian runs
-- exactly as before. Without this block, AI is off entirely.
--
-- The helper needs these Python packages: `openai`, and for broker auth
-- `azure-identity-broker` (and `pywin32` for the sign-in dialog's parent
-- window). Data sent to the model is only what a feature needs (file names and
-- sizes; file contents only when a feature explicitly requires it).
--
-- There is no default endpoint. A site's own API gateway belongs in that
-- site's init.lua rather than in the source of a public program, so the AI
-- features say what to set rather than reaching for someone else's address.
--
-- Set it like this:
-- cian.ai {
--   endpoint    = "https://your-apim.azure-api.net/llmaoai",  -- Azure OpenAI / APIM
--   model       = "gpt-5-mini",
--   auth_mode   = "broker",    -- "broker" (Windows AAD), "apikey", or "mock" (offline echo)
--   -- python   = "python",    -- interpreter to use (default: "python")
--   -- api_version  = "2025-04-01-preview",
--   -- api_key      = "...",   -- only for auth_mode = "apikey"
--   -- api_base_url = "http://localhost:11434/v1",  -- Ollama / LM Studio (OpenAI-compatible)
-- }
--
-- 404 "Resource not found"? With broker/Azure auth the `model` is the DEPLOYMENT
-- NAME and lands in the request URL (…/openai/deployments/<model>/chat/…), so a
-- wrong one 404s — set `model` (and `api_version`) to match your working client.
-- If instead your gateway is OpenAI-compatible (it wants /chat/completions with
-- the model in the body, not the /openai/deployments/ path), set `api_base_url`
-- to the gateway base and cian will use that route with the broker token:
-- cian.ai {
--   auth_mode    = "broker",
--   api_base_url = "https://your-apim.azure-api.net/llmaoai",  -- OpenAI-compatible route
--   model        = "<your model>",
-- }
--

-- ----------------------------------------------------------------------------
--  Japanese input (IME) — all but required if you use the vim grammar
-- ----------------------------------------------------------------------------
--  **With the IME on, normal-mode keys never reach cian.** The input method
--  holds a keystroke until it is committed, so `j`, `i` and `?` do not arrive
--  at all. This is true in the terminal build and in the window, and it is
--  the same reason vim users install `im-select`.
--
--  Configured, cian switches it **for you, by mode**: off whenever a key is a
--  command, and back to **the source you were last typing with** wherever
--  text is being taken (insert mode, rename, the command line).
--
--  The helper ships with cian. There is nothing to install from elsewhere.
--
--  macOS — one compile (thirty lines over the system API):
--    swiftc -O -o ~/.local/bin/cian-ime examples/cian-ime.swift
--
-- cian.ime{
--   helper = "$HOME/.local/bin/cian-ime",
--   off    = "com.apple.keylayout.ABC",   -- run `cian-ime` with no argument
-- }                                       -- to print the current source id
--
--  Windows — nothing to compile; PowerShell runs it as it is:
--
-- cian.ime{
--   helper = [[powershell -NoProfile -File C:\Users\you\cian-ime.ps1]],
--   off    = "off",
-- }
--
--  Note that Windows' IME is **open or closed per window**, which is a
--  different thing from macOS' "switch the input source" — so its two ids are
--  the words "on" and "off". cian never looks inside the string, so the same
--  mechanism fits both.
--
--  `macism` or `im-select` work too if you already have one
--  (`helper = "macism"`). For an odder helper, give `query` and `set`
--  separately (`set = "switch --to {}"`).
--
--  **`:ime` is the diagnosis.** It shows what is configured, what source is
--  remembered, and what the last switch did. `:ime on` / `:ime off` try it.
